//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long Note_Id { get; set; }
        public string Note_Name { get; set; }
        public long Note_ProductId { get; set; }
        public long Note_PageId { get; set; }
        public string Note_Content { get; set; }
        public System.DateTime Note_CreatedDate { get; set; }
        public Nullable<System.DateTime> Note_ModifiedDate { get; set; }
    }
}
